import tkinter as tk
import os
from pathlib import Path

def quit():
    exit()

def on_button_click():
    print("e")
    label.config(text="Button Pressed!")

def generatefiles():
    for i in range(5):
        file = Path(f"example{i}.txt")
    for i in range(200):   
        file.write_text("This file is bloat and was generated by the Bloatinator!")


root = tk.Tk()
root.title("Rude Assistance")

# Create a label
label = tk.Label(root, text="Options")
label.pack()

# Create a button that calls `on_button_click` when pressed
genbutton = tk.Button(root, text="Generate fake files", command=generatefiles)
gencustombutton = tk.Button(root, text="Generate fake files with custom size", command=on_button_click)
genviewbutton = tk.Button(root, text="View generated fake files", command=on_button_click)
gendeletebutton = tk.Button(root, text="Delete all fake files", command=on_button_click)
quitbutton = tk.Button(root, text="Quit (and fail your tasks)", command=quit)

genbutton.pack()
gencustombutton.pack()
genviewbutton.pack()
gendeletebutton.pack()
quitbutton.pack()

# Run the Tkinter event loop
root.mainloop()
