import tkinter as tk
import os
from pathlib import Path

def quit():
    exit()

def on_button_click():
    print("e")
    label.config(text="Button Pressed!")

def generatefiles():
    for i in range(5):
        file = Path(f"example{i}.txt")
    for i in range(200):   
        file.write_text("This file is bloat and was generated by the Bloatinator!")


root = tk.Tk()
root.title("Rude Assistant")

# Create a label
label = tk.Label(root, text="Options")
label.pack()

# Create a button that calls `on_button_click` when pressed
genbutton = tk.Button(root, text="Generate fake files", command=generatefiles)
gencustombutton = tk.Button(root, text="Generate fake files with custom size", command=on_button_click)
genviewbutton = tk.Button(root, text="View generated fake files", command=on_button_click)
gendeletebutton = tk.Button(root, text="Delete all fake files", command=on_button_click)
quitbutton = tk.Button(root, text="Quit (and fail your tasks)", command=quit)

genbutton.pack()
gencustombutton.pack()
genviewbutton.pack()
gendeletebutton.pack()
quitbutton.pack()


def show_page(page):
    page.tkraise()

container = tk.Frame(root)
container.pack(fill="both", expand=True)

# Create pages
page1 = tk.Frame(container)
page2 = tk.Frame(container)

for page in (page1, page2):
    page.grid(row=0, column=0, sticky="nsew")

# Page 1
tk.Label(page1, text="This is Page 1", font=("Arial", 16)).pack(pady=10)
tk.Button(page1, text="Go to Page 2", command=lambda: show_page(page2)).pack()

# Page 2
tk.Label(page2, text="This is Page 2", font=("Arial", 16)).pack(pady=10)
tk.Button(page2, text="Back to Page 1", command=lambda: show_page(page1)).pack()

# Show first page initially
show_page(page1)

# Run the Tkinter event loop
root.mainloop()
