import tkinter as tk
import os
from pathlib import Path
import sys


def quit():
    exit()

def on_button_click():
    buttonbox("hi")
    print("e")
    label.config(text="Button Pressed!")

def generatefiles():
    for i in range(5):
        file = Path(f"example{i}.txt")
    for i in range(200):   
        file.write_text("This file is bloat and was generated by the Bloatinator!")


root = tk.Tk()
root.title("Rude Assistant")

# Create a label
label = tk.Label(root, text="Options")
label.pack()

# Create a button that calls `on_button_click` when pressed

def show_page(page):
    page.tkraise()

container = tk.Frame(root)
container.pack(fill="both", expand=True)

# Create pages
page1 = tk.Frame(container)
page2 = tk.Frame(container)

for page in (page1, page2):
    page.grid(row=0, column=0, sticky="nsew")

# Page 1
tk.Label(page1, text="Main menu", font=("Arial", 16)).pack(pady=10)
tk.Button(page1, text="Tasks", command=lambda: show_page(page2)).pack()

# Page 2
tk.Label(page2, text="Tasks", font=("Arial", 16)).pack(pady=10)
tk.Button(page2, text="Main menu", command=lambda: show_page(page1)).pack()
genbutton = tk.Button(page2, text="Generate fake files", command=generatefiles)
gencustombutton = tk.Button(page2, text="Generate fake files with custom size", command=on_button_click)
genviewbutton = tk.Button(page2, text="View generated fake files", command=on_button_click)
gendeletebutton = tk.Button(page2, text="Delete all fake files", command=on_button_click)
quitbutton = tk.Button(page2, text="Quit (and fail your tasks)", command=quit)

genbutton.pack()
gencustombutton.pack()
genviewbutton.pack()
gendeletebutton.pack()
quitbutton.pack()

# Show first page initially
show_page(page1)

# Run the Tkinter event loop
root.mainloop()
